//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlytrotdm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSEGER
    {
        public int IDMESS { get; set; }
        public Nullable<int> IDMOTEL { get; set; }
        public Nullable<int> IDSTUDENT { get; set; }
        public string CONTENT { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual MOTEL MOTEL { get; set; }
    }
}
