//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlytrotdm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE
    {
        public int IDPRICE { get; set; }
        public Nullable<int> PRICE1 { get; set; }
    }
}
